automata/fa/dfa.py
requirements.txt
setup.py

Add graph visualization feature for DFA.
TODO: Working on the other types of graphs

Graph visualization

---

README.md
automata/fa/dfa.py
tests/test_dfa.py

Implementation for #24. Includes the following operations:
- Empty check
- Disjoint check
- Subset check
- Superset check
- Equivalence check
- Complement
- Union
- Intersection
- Set difference
- Symmetric difference

DFA Operations

---

automata/fa/nfa.py
tests/test_nfa.py

Implementation of reverse (`__reversed__`), concatenation (`__add__`) and kleene star.

NFA Operations: Reverse, Concatenation, and Kleene Star

---

automata/fa/dfa.py
automata/fa/fa.py
pyproject.toml
requirements.txt

Resolves #47. Uses a faster algorithm for checking equality for DFAs, and adds networkx dependency. @caleb531 should be good for review. Kinda unfortunate that you can't really see the performance improvement in the unit tests, but for large DFAs it's definitely noticeable.

Added networkx dependency and faster equality algorithm

---

automata/fa/dfa.py

Refactor DFA functions to leverage networkx package.

DFA networkx refactor

---

automata/fa/dfa.py

Sped up a couple DFA algorithms, and changed some to use comprehension style. Possibly a bit extra, but copied from our implementations of these functions, so figured why not. Also remembered to run flake8 this time.

Faster DFA algorithms

---

README.md
automata/base/exceptions.py
automata/fa/dfa.py
automata/fa/fa.py
automata/fa/nfa.py
tests/test_dfa.py

Added specialized algorithms for subset and disjointness checking. Uses networkx to avoid explicitly constructiong + validating a new DFA to run these comparison functions. In our local repo, this sped up our CI job considerably.

Even faster comparison algorithms

---

README.md
automata/fa/nfa.py
tests/test_gnfa.py
tests/test_nfa.py

Implemented NFA.to_regex() with added tests. Updated README

---

README.md
automata/fa/dfa.py
tests/test_dfa.py

NFA conversion fix

---

automata/base/utils.py
automata/fa/dfa.py

Modifications that significantly speed up the minify algorithm. Will post benchmarks soon, but seeing 10x speedup in some early tests. @caleb531 Should be mostly complete, will do one more pass before merging. Figured it was better to have a version up ASAP rather than waiting for things to be flawless.

Optimized the DFA.minify() algorithm

---

automata/base/utils.py
automata/fa/dfa.py

Sorry! 😅  While integrating the code into our codebase, noticed a subtle bug that caused the tests to fail very infrequently (like 1 out of every 20 runs). Also, cleaned up variable names to more closely match the wikipedia article: https://en.wikipedia.org/wiki/DFA_minimization#Hopcroft's_algorithm

Fixed a bug with the partition algorithm

---

automata/regex/parser.py

@caleb531 Removes redundant function in constructor of a class in parser.

Remove unnecessary function in parser

---

automata/fa/dfa.py
automata/fa/nfa.py
tests/test_nfa.py

Putting up as a draft PR because my local test runner is being weird. Part of inital set of rewrites in preparation for enforcing immutability.

Initial immutability rewrites

---

automata/fa/gnfa.py

@caleb531 see title. Functions are a bit confusing so could maybe be refactored more, but a solid start I think.

Switch GNFA functions to respect immutability

---

automata/fa/gnfa.py

Refactor GNFA to regex to comply with immutability and be iterative @caleb531 
EDIT: Whoops, need to rebase real fast.

Refactor GNFA to_regex

---

automata/fa/dfa.py
tests/test_dfa.py

Added algorithm to compute minimal DFA from given finite language. Still a bit of a WIP, but should be good to go soon.
@caleb531 marked ready for review (since tests cases are passing and style is good), though I think the merge conflict is from changes you're making. Not sure if you wanted to make more changes to the base branch before I resolved the conflict.

Added minimal DFA for finite language algorithm

---

README.md
automata/fa/nfa.py
tests/test_nfa.py

Adds an NFA intersection algorithm with unit tests. @caleb531 sorry to say but, the tests couldn't use the native NFA equality checking algorithm (as it was raising errors). I think there may be a bug 😬

Add NFA.intersection()

---

automata/regex/regex.py

@caleb531 Uses a cleaner regex subset algorithm (using NFA library calls to avoid DFA conversion). It might be a bad idea to include this as an NFA method directly (since it creates a new intermediate NFA), but this recipe should probably go in the documentation.

Cleaned up regex subset algorithm

---

README.md
automata/base/automaton.py
automata/fa/dfa.py
tests/test_dfa.py

Code for #79 
I had to update the copy function in automaton to skip copying the caches. Don't really like the fix I made.
Rest is just as discussed and then added min and max word length functions which are calculated with BFS and longest path in DAG, respectively.

Enumeration and iteration for DFA

---

automata/base/utils.py
automata/fa/dfa.py
automata/fa/nfa.py
tests/test_nfa.py

@caleb531 Adds some extra tests for regex parsing to NFAs and style in DFA minimization.

NFA extra test

---

automata/fa/nfa.py
tests/test_gnfa.py
tests/test_nfa.py

@caleb531 Fixes a bug in NFA equality and switches other tests to use that algorithm (some of these were failing before the bugfix).

NFA equality bugfix

---

README.md
automata/fa/dfa.py
tests/test_dfa.py

Added the following construction helpers:
- `universal_language`
- `empty_language`
- `from_substring`
- `from_subsequence`
- `from_prefix`
- `from_suffix`
- `of_length`
- `count_mod`
- `nth_from_end`
- `nth_from_start`

Add DFA construction helpers

---

automata/base/automaton.py
automata/base/utils.py
automata/fa/dfa.py
automata/fa/gnfa.py
automata/fa/nfa.py
automata/pda/dpda.py
automata/pda/npda.py
automata/regex/lexer.py
automata/regex/parser.py
automata/tm/dtm.py
automata/tm/mntm.py
automata/tm/ntm.py
tests/test_dfa.py
tests/test_dpda.py
tests/test_dtm.py
tests/test_gnfa.py
tests/test_mntm.py
tests/test_nfa.py
tests/test_npda.py
tests/test_ntm.py

@eliotwrobson Posting this PR with my `__slots__` implementation to get your feedback, when you have time.

Implement __slots__ everywhere

---

README.md
automata/fa/nfa.py
automata/regex/lexer.py
automata/regex/parser.py
tests/test_regex.py

@caleb531 Added intersection and kleene plus to regex syntax. Open to adding more syntax (like a wildcard, for example), but those would require modifying the interface for the current regex to NFA conversion.
EDIT: cc @Tagl not sure if you have any ideas for more regex syntax.

Extended regex syntax

---

README.md
automata/fa/dfa.py
tests/test_dfa.py

Added function for uniform random generation for words of length k in DFA

DFA Uniform random word

---

README.md
automata/fa/dfa.py
automata/fa/nfa.py
tests/test_dfa.py
tests/test_nfa.py

Adds left and right quotient operators for NFAs with tests. Tests are a little basic, and the construction is a little rough around the edges, but overall should be solid. @caleb531 @Tagl

Add left and right quotient operators

---

automata/fa/dfa.py
automata/fa/nfa.py

@caleb531 Simplifies some internal functions to the DFA class, including more efficient construction of cross product transitions. Also, switches many functions to create frozensets to avoid additional copies.

Simplify internal DFA functions

---

automata/fa/nfa.py
automata/regex/parser.py
automata/regex/regex.py
docs/regular-expressions.md
tests/test_regex.py

Adds wildcard `.` to the regex syntax. Also makes some regex functions more robust. Leaving as a draft until my other PR is merged.

Add wildcard character to regex

---

automata/fa/gnfa.py
docs/fa/class-dfa.md

Updates style of GNFA class. Should improve efficiency.

GNFA style

---

automata/base/utils.py

Switches utility function to use default dict.

Switched to default dict

---

automata/base/automaton.py
automata/fa/dfa.py
automata/fa/gnfa.py
automata/fa/nfa.py
automata/pda/pda.py
automata/regex/regex.py
automata/tm/dtm.py
automata/tm/mntm.py
automata/tm/ntm.py
tests/test_regex.py

See title, resolves https://github.com/caleb531/automata/issues/135

Validate type change

---

automata/fa/fa.py
automata/fa/nfa.py
automata/pda/dpda.py
automata/pda/pda.py
automata/tm/mntm.py
automata/tm/tm.py

@caleb531 see title. Fixed an issue with slots and added types + simplified a function in the MNTM class.

More type hints and slots fix

---

automata/fa/dfa.py

Minor optimizations

---

automata/base/utils.py
automata/fa/dfa.py
automata/fa/fa.py
automata/fa/nfa.py
automata/pda/dpda.py
automata/pda/npda.py
automata/regex/postfix.py
automata/tm/configuration.py
automata/tm/mntm.py
pyproject.toml
tests/test_config.py
tests/test_dfa.py
tests/test_dpda.py
tests/test_dtm.py
tests/test_mntm.py
tests/test_nfa.py
tests/test_npda.py
tests/test_ntm.py
tests/test_pda.py
tests/test_pdaconfiguration.py
tests/test_pdastack.py
tests/test_postfix.py
tests/test_serialization.py
tests/test_tm.py
tests/test_tmconfiguration.py
tests/test_tmtape.py
tests/test_tmtools.py

Add more type hints to test cases

---

joss/paper.bib

Reference still being annoying

---

automata/base/utils.py
automata/fa/dfa.py
automata/regex/parser.py
automata/regex/postfix.py

See title. Adds pairwise helper function and simplifies some pairwise iterations (avoids making unnecessary copies of lists). Mostly a style thing.

Add pairwise helper function

---

README.md

See title, resolves #174. @mahfuz05062 if this looks good, we can go ahead and merge.

Added link to contributing guide to README.md

---

automata/fa/dfa.py
docs/api/fa/class-dfa.md
mkdocs.yml

See title, changing the mkdocs config to work with the DFA class.

Started adding DFA docstrings

---

automata/base/utils.py

fix: Type was too general

---

automata/fa/dfa.py
tests/test_dfa.py

Reverts caleb531/automata#224
Whoops, committed to the wrong branch.

Revert "Successors length limits"

---

mkdocs.yml
requirements.docs.txt

Fixed docs site by removing unused keys in config.

Docs site fixed

---

automata/fa/dfa.py
tests/test_dfa.py

Fixed bug and added test. Resolves #257

Fix small bug in minifying partial DFAs
