caleb531/automata

automata/fa/dfa.py
tests/test_dfa.py

I had an issue converting a NFA (which is a little bit complex) to a DFA, so I took a look at how the conversion works. I came up with these changes:
* There's no need to re-compute transitions we've already done, so let's skip those.
* Also let's rely on the queue to determine whether we're done.
This seems to produce more correct results.
I tried to add a minimal example to the tests.

Optimize and improve DFA.from_nfa (and add a test for this change).

---

README.md
automata/fa/dfa.py
tests/test_dfa.py

A given DFA can be minified by first removing unreachable states and then merging equivalent states.
I've implemented `DFA.minify` (which seems to work, but I'm not exactly sure), added two tests for this (I didn't add tests for `_remove_unreachable_states`, `_compute_reachable_states`, `_create_markable_states_table`, `_mark_states_table_first`, `_mark_states_table_second` and `_join_non_marked_states`) and added a bit of documentation.

Minify DFAs

---

README.md
automata/tm/dtm.py
automata/tm/tape.py
tests/test_dtm.py

Today, I first tried simulating a DTM. And it didn't work, because the DTM I tried had transitions which didn't move the head.
This PR quickly implements this feature.
A few thoughts:
* I didn't change the DTM in the README to make use of this.
* I don't know if this `elif direction == 'N': pass` makes sense.
But because the other two cases were present in the function, I figured it would be nice.
* I didn't add any tests. (There's just a little bit new code, if any. - Let's see if Coveralls complains.)

TM: Support not moving (direction N)

---

README.md
automata/pda/configuration.py
automata/pda/dpda.py
automata/pda/npda.py
automata/pda/stack.py
tests/test_dpda.py
tests/test_npda.py
tests/test_pda.py
tests/test_pdaconfiguration.py
tests/test_pdastack.py

This pull request adds a new class `NPDA` which represents nondeterministic pushdown automata.
**It will probably break existing code using DPDAs.** Sorry about that.
So, what it does is basically the following:
* `PDAStack` becomes immutable and hashable. It still represents the current stack of a PDA.
* `PDAConfiguration` is new. This is a (immutable and hashable) class representing the current configuration of a PDA. It is basically a tuple of state, remaining input and stack. `DPDA` has been changed to use it.
* `DPDA._get_next_configuration` is the main thing, now.
* A step in `read_input_stepwise` is now one transition and not one read symbol.
* `DPDA._has_accepted` is new. (It does what the name says it does.)
* `NPDA` is new. It is very similar to `DPDA`; the main difference is …

Add support for NDPAs

---

README.md
automata/tm/configuration.py
automata/tm/dtm.py
automata/tm/ntm.py
automata/tm/tape.py
automata/tm/tools.py
tests/test_dtm.py
tests/test_ntm.py
tests/test_tm.py
tests/test_tmtools.py

This pull request adds a new class `NTM` which represents nondeterministic Turing machines. It is conceptually very similar to #9.
This might break code which relies on the string representations of the tape or configuration of Turing machines. Otherwise, it should be fine, I think.
So, what it does is basically the following:
* `TMTape` becomes immutable and hashable. It still represents the tape of a TM and the current cursor position. (I've removed the offset stuff; I'm not sure about this.)
* `TMConfiguration` is new. This is a (immutable and hashable) class representing the current configuration of a TM. It is basically a tuple of state and tape. Also, `tmtools.print_config` has been moved here.
* `DTM` has been adjusted to these changes.
* `DTM._get_next_configuration` is the main …

Add support for NTMs

---

MIGRATION.md
README.md
automata/pda/dpda.py
automata/pda/exceptions.py
automata/pda/npda.py
automata/pda/pda.py
tests/test_dpda.py
tests/test_npda.py
tests/test_pda.py

This is related to issue #8.
I implemented the feature (which was a small change) and adjusted the documentation and tests.
I didn't add a test for the case where one mode is specified and the other occurs, though.

Make acceptance mode of PDAs configurable.

---

automata/fa/dfa.py

In the breadth first search implementation in `_compute_reachable_states`, when processing the neighbours of a given vertex, for each vertex we check whether it is in `states_checked` and if not push it to the `states_to_check` queue, however, we only add each vertex to `states_checked` once we actually reach that vertex. This could lead to lots of duplication of vertices in the queue, with potentially a O(V * deg(V)) -> worst-case O(V^2) runtime.
Fixing this bug (in other words, adding to the visited set at the same time as we push the vertex to the queue) takes the runtime for minimising ~5000 fairly large DFAs (with around 6 states each after minimisation) from hours to a few minutes.
In addition, as it does not appear to be the case that we need thread-safe processing for the queues …

Optimisation for DFA minimisation

---

automata/fa/dfa.py

Currently the graphviz/DOT output does not include marking the final states. This commit changes that.

Now marking final states in the DOT output for DFAs

---

README.md
automata/base/automaton.py
automata/base/exceptions.py
automata/base/regex.py
automata/fa/dfa.py
automata/fa/gnfa.py
automata/fa/nfa.py
tests/test_dfa.py
tests/test_dtm.py
tests/test_fa.py
tests/test_gnfa.py
tests/test_mntm.py
tests/test_nfa.py
tests/test_ntm.py
tests/test_regex.py
tests/test_tm.py
tests/test_tmtools.py

Thanks for this nice library. 
So basically, I have worked on converting an NFA/DFA to regular expression and also backward, regular expression to NFA conversion. All other changes were done to help this task, test it, and remove existing errors.
1. New class added: GNFA - Generalised Nondetermistic Finite automaton. (as `automata/fa/gnfa.py`). I have added a description of GNFA in `README.me` explaining its characteristics.
- `GNFA.from_nfa(cls, nfa)`
- `GNFA.from_dfa(cls, dfa)`
- `GNFA.to_regex(self)` #13 
- `GNFA.show_diagram(self, path=None, show_None = True`
All other functions were defined as helper functions or for initializing the class. Check `README.me` for all additions.
2. Additions /Changes to NFA (`automata/fa/nfa.py`)
- `NFA.from_regex(cls, regex)` #13 
- …

Regular Expression conversions in both direction + NFA.eliminate_labmda + some other functions and changes

---

automata/fa/dfa.py

Refactor the `from_nfa` function to reduce the number of function calls and make code simpler. Should increase speed since function calls can get expensive, and this section of the code can run an exponential number of times.

Refactor DFA.from_nfa function

---

automata/fa/dfa.py
automata/regex/parser.py

@caleb531 Replaces an out-of-date comment and removes the concat token from the regex parser (since the concatenation operator is implicit and not part of the syntax in the documentation).

Remove concat token from parser and fix old comment

---

automata/fa/dfa.py

Removes some redundant set conversions in DFA.from_nfa function. Noticeable performance improvement in some benchmarks.

Remove some set conversions in DFA.from_nfa()

---

automata/fa/dfa.py
automata/fa/gnfa.py
automata/fa/nfa.py

@caleb531 turns out it's faster in some cases to do BFS directly instead of reading all states of a product graph into a data structure (since this effectively makes two passes through the data instead of 1). Networkx implements the same algorithm anyway in pure Python. Saw 10x speedup in some cases.

Optimize reachable states algorithms

---

README.md
automata/fa/dfa.py
automata/regex/parser.py
automata/regex/regex.py
tests/test_dfa.py
tests/test_tm.py

@caleb531 Refactors the minify and cross product functions to avoid creating intermediate DFAs. Cross product function now returns only reachable part of the product DFA by default.

Refactor DFA.minify()

---

README.md
automata/fa/dfa.py
automata/fa/nfa.py
tests/test_dfa.py
tests/test_nfa.py
tests/test_regex.py

Adds shuffle product operation for NFAs. Creates an NFA that accepts interleavings of component languages. Seen this construction in some articles / other automata packages, so thought it was worth including for completeness.

Add shuffle product operation

---

README.md
automata/base/automaton.py
automata/base/config.py
tests/test_config.py

Adds a new `automata.base.config` module with the following members:
1. A `Config` class that is only used for instantiating the `global_config` instance mentioned below
2. A single `Config` instance called `global_config`, which is referenced in the `automata.base.automaton` module.
README documentation still needs to be added.
@eliotwrobson @Tagl I welcome your feedback on the code I've written so far.

Add global configuration and allow disabling automaton validation

---

automata/base/automaton.py
automata/base/config.py
automata/base/utils.py
docs/class-automaton.md
tests/test_config.py

This commit speeds up the freezeValue method, which is the main bottleneck of automata creation. There are two optimizations:
* Move the most frequent types up the if chain to hit it as early as possible
* Offer the option to disable the freezeValue call completely (the user must guarantee that the values are frozen or accept that the library might break)
When benchmarking the creation of an automata accepting the language a*, we see that disabling the freezeValue call yields a speedup of 3 times if the values are not frozen and 2 times if the values are frozen.
The small overhead introduced by checking the ensure_frozen flag is compensated by the reordering of if statements

Speed up Automata Creation

---

automata/regex/parser.py
docs/regular-expressions.md
tests/test_regex.py

Added shuffle product to regex. @EduardoGoulart1 and @caleb531 resolves part of the issue in #109.

Shuffle regex

---

automata/base/utils.py
automata/fa/dfa.py
automata/fa/nfa.py
automata/regex/parser.py
tests/test_dfa.py

Add retain names functionality to cross product. Resolves an inconsistency with expected behavior and should improve efficiency of minify function.
EDIT: Don't merge yet, just found a really dumb subtle bug in here. This also needs to wait until the shuffle product PR is merged, since that issue is present there as well (not a breaking bug).

Resolve retain names issue

---

automata/fa/nfa.py
tests/test_nfa.py

@caleb531 The NFA `_from_symbol` function was only being used as part of the old regex parsing algorithm and the functionality was a less general version of what's currently available with the DFA `from_finite_language` function. This PR removes `_from_symbol`.
As an aside, it _could_ be worth adding some NFA construction algorithms, but if we do then they should be more general than this function was.

Removed NFA._from_symbol method

---

automata/base/utils.py
automata/fa/gnfa.py
tests/test_gnfa.py

@caleb531 Resolves #122 and adds tests to catch bug in the future. Fix is due to @abhinavsinha-adrino.

GNFA regex bug fix 

---

automata/base/automaton.py
tests/test_serialization.py

The initial use-case that I stumbled upon was to serialize DFAs with pickle. I would get an error because it was calling __setattr__, which is disabled even though I was setting the `allow_mutable_automata` flag.
If we allow for mutable automata, then one should be able to modify its attributes.
```python
global_config.allow_mutable_automata = True
dfa_1 = DFA(
states={0, 1},
input_symbols={0, 1},
transitions={0: {0: 1, 1: 0}, 1: {0: 1, 1: 1}},
initial_state=0,
final_states={1},
)
with open('dfa.pkl', 'wb') as f:
pickle.dump(dfa_1, f)
with open('dfa.pkl', 'rb') as f:
dfa_1_read = pickle.load(f)
assert dfa_1 == dfa_1_read
```
**Edit:** After some consideration, I decided to disable set/get attributes as this will mess with the `validate` function. Instead serialization is implemented …

Support for pickling of finite automata

---

automata/fa/dfa.py
automata/fa/nfa.py
automata/regex/parser.py

Uses a new counter each time a regex gets parsed. This is useful because parsing multiple regexes could use a large number of states, and having the complexity of the state name increase too much could slow things down.
Also, small changes to iteration logic (using `zip-repeat` which is faster than `product`), and `isdisjoint` for faster set intersection checking.

Better numbering usage + other small updates

---

automata/regex/parser.py
automata/regex/postfix.py
automata/regex/regex.py
docs/regular-expressions.md
tests/test_nfa.py
tests/test_regex.py

Added empty string to regex with `()`. Resolves #128.

Regex empty string

---

automata/fa/dfa.py
automata/fa/nfa.py

@eliotwrobson Just wanted to get your thoughts on this—I noticed that we still use explicit class types as return types in many places (e.g. `-> DFA` and `-> NFA`). But if we have access to the `Self` and `Type[Self]` types, then these should not be needed, correct?
Per my commit note in this PR, using `Self` where applicable should also eliminate those `TypeVar` types (i.e. `DFAType`), which is actually one of the reasons why `Self` was introduced (see [the "Use in Classmethod Signatures" section in PEP 673](https://peps.python.org/pep-0673/#use-in-classmethod-signatures)).
Anyway, please let me know what you think of this!

Use Self type where applicable

---

automata/pda/configuration.py
automata/pda/dpda.py
automata/pda/stack.py
automata/tm/configuration.py
automata/tm/tape.py
tests/test_dtm.py
tests/test_mntm.py
tests/test_ntm.py
tests/test_pdaconfiguration.py
tests/test_pdastack.py

@eliotwrobson Alright, here's my attempt to refactor the PDAStack and `*Configuration` classes to use dataclasses instead of namedtuple inheritance. 
I decided to keep the casting to a tuple on instantiation because I felt it was more consistent with the type-casting we are performing currently for the automaton subclasses. Plus, it is just easier to work with because I don't have to remember to explicitly pass a tuple to the constructor
As I was looking at the `PDAStack` class, I was noticing how the `PDAStack` is basically a glorified wrapper for the `stack` tuple underneath. Semantically, they represent the same thing, with no difference in data but only difference in behavior. Therefore, I was thinking: maybe we could just inherit directly from `Tuple[str, ...]`, which would eliminate …

Refactor *Stack / *Configuration classes to be dataclass-based

---

automata/fa/dfa.py
automata/fa/fa.py
automata/fa/gnfa.py
automata/fa/nfa.py
automata/regex/lexer.py
automata/regex/parser.py
docs/fa/class-gnfa.md
docs/fa/class-nfa.md
tests/test_automaton.py
tests/test_config.py
tests/test_dfa.py
tests/test_fa.py
tests/test_gnfa.py
tests/test_lexer.py
tests/test_nfa.py
tests/test_postfix.py
tests/test_regex.py

@caleb531 See title. A number of small changes accompanied this, to make the adoption of type hints simpler.
- `GNFA` no longer inherits from `NFA`. There was very little actual logic sharing between these classes. This eliminated the need for some redundant tests.
- Some minor changes to the internals of the regex lexer (some methods were just not needed).
- Removed `__reversed__` method for `NFA` class, since this method has different intended usage (should be used on sequences).

Start adding type hints to test cases

---

docs/fa/examples.md

Add an example of creating a transition table, adapted from visual automata. This is part of the deprecation of visual automata in #124, as it was decided that we did not want to add pandas as a dependency for this library. Thus, the best course of action was to add snippets of code from that library that would have introduced dependencies as examples.
Should wait for #129 before merging, as this code uses a method introduced there.
@lewiuberg please let me know what you think if you get the chance.

Transition table example

---

automata/base/automaton.py
automata/fa/dfa.py
automata/fa/nfa.py
docs/fa/class-dfa.md
pyproject.toml
requirements.txt
tests/test_dfa.py
tests/test_nfa.py

See title, adds a word cache reset function and precomputes the digraph used by the DFA. Resolves #148 
In looking at this, I thought about using a cached property for some of the methods that return fixed information about the given DFAs. However, switching these to cached properties (with the decorator) requires using a slightly different API. @caleb531 what are your thoughts about changing this? Is there a way to provide this caching without changing the API? It would be great if there were a way to do this cleanly.

Add word cache reset function

---

automata/fa/dfa.py
automata/fa/fa.py
automata/fa/nfa.py
docs/fa/class-dfa.md
pyproject.toml
tests/test_dfa.py
tests/test_gnfa.py

@eliotwrobson @caleb531 Please do not review it because the code is not ready yet. This is just a draft to book progress on the allow_partial support.
If you go with the definition that DFAs are sets of words, then all operations are well-defined and relatively easy to implement. Most of the times the only required change is to replace loops like:
```Python
for symbol in input_symbols:
tgt_a = transitions_a[symbol]
```
By the code:
```Python
for symbol in input_symbols:
tgt_a = transitions_a.get(tgt_a, None)
```
I made the code such that it adds no overhead for complete DFAs compared to the current implementation. For partial DFAs, if the DFAs are sparse, then you will get a large performance boost, while if they are dense you will pay some penalty (but most of the times negligible).
I …

Proper support for allow_partial

---

joss/paper.bib
joss/paper.md

Paper edits

---

joss/paper.bib
joss/paper.md

See title, another dummy PR to cut down on the number of commits to develop.

More paper edits

---

automata/base/automaton.py
automata/base/exceptions.py
automata/base/utils.py
automata/fa/fa.py
automata/pda/configuration.py
automata/pda/dpda.py
automata/pda/npda.py
automata/pda/pda.py
automata/pda/stack.py
docs/base-exception-classes.md
docs/pda/class-pda.md
tests/test_dpda.py
tests/test_fa.py
tests/test_npda.py
tests/test_pda.py
tests/test_pdaconfiguration.py
tests/test_pdastack.py

Implemented the `show_diagram` method for Push Down Automata.
I have just adapted the `FA.show_diagram` (Finite Automata) code for `PDA.show_diagram`.
I have not yet implemented `show_diagram` with `input_str`. I will require some suggestions here. Should I also show the operations performed on the stack, or only the state transitions are sufficient?
I have not tested the code, except for `DPDA` and `NPDA` in the docs. I have attached the images below.
DPDA:
NPDA:
Reminder for myself and the maintainer: I should also update the docs to reflect the new feature, before merging this PR.
Hope this is helpful. Please let me know if any changes are required.
---
Edited:
I have implemented the construction of the diagram with an `input_str`.
DPDA from docs with `input_str = "aabb"`:
NPDA from …

Added `show_diagram` method for Push Down Automata

---

automata/fa/dfa.py
tests/test_dfa.py

Resolves #182. Modifies the algorithm to deal with partial DFAs correctly. Somewhat inefficient, but the best we can do until Valmari's algorithm gets implemented (which is a separate open issue).
cc @martinec. If you have any more potentially interesting test cases, would be good to add to make sure the algorithm is working correctly (this one is unfortunately a bit tricky to get right).

fix: Minify for partial DFAs

---

docs/characteristics.md
mkdocs.yml

Added back missing docs page from move to mkdocs. Uses change from #194

Adding back missing docs

---

.github/workflows/docs.yml
.vscode/settings.json

One of the last PRs for #160! I think all that needs to be done is set the publish source branch for this page is `gh-pages` (per the instructions here: https://squidfunk.github.io/mkdocs-material/publishing-your-site/#with-github-actions).
I haven't played around with this too much, so I can't quite verify that it works. I think the way to handle it might be to have the workflow run on pushes to develop, then check that the github pages is working as expected. Then, we can remove that trigger once everything is set up. @caleb531 what are your thoughts? This might require some fiddling on your end.

Add docs workflow

---

.github/workflows/docs.yml
README.md

See title, updates readme links to new documentation.
Also, removed the publish trigger for pushes to the develop branch. Once this is merged, all that's needed should be a merge to master! @caleb531 once that's done, I can open the submission.

Readme update

---

LICENSE.txt
README.md
docs/index.md
mkdocs.yml

@eliotwrobson Just something I noticed and wanted to correct. I didn't change anything else, since it makes sense to me to remove the irrelevant README badges for the documentation site. Same for the links to the other documentation pages, as the links would probably break / navigate to the incorrect files anyway (we want to keep the user in the documentation site, after all).
One other thing: does `automata-lib[visual]` really require quotes to install?
```sh
pip install 'automata-lib[visual]'
```
...versus just:
```sh
pip install automata-lib[visual]
```

Update copyright notice of docs index page

---

.github/workflows/lint.yml
pyproject.toml
setup.py

Some small changes suggested by this comment from the review: https://github.com/pyOpenSci/software-submission/issues/152#issuecomment-1900695651
Ran the build command locally and seems to work? Not 1000% sure if I tested this correctly, but I think fairly reasonable changes.

fix: Small changes from comment

---

.vscode/extensions.json

@eliotwrobson Just a small quality-of-life improvement, but with a small caveat, and so want your feedback.
This commit switches the third-party cornflakes-linter VS Code extension
to the official Flake8 extension by Microsoft. I'm hoping this should fix an issue I've encountered with the former extension where files
within the virtualenv or within Python stdlib were linted when they
should have been ignored. I haven't tested that the new extension fixes this, but given that it's first-party, I'm optimistic that it's less buggy.
The catch with this change is that anyone who has installed the official Flake8 extension should uninstall cornflakes-linter (or disable it for the workspace) lest they see duplicate errors in the Problems panel (or otherwise experience other unforeseen conflicts …

Use official Flake8 VS Code extension

---

.github/workflows/build.yml
.github/workflows/lint.yml
.github/workflows/publish.yml
.github/workflows/tests.yml
requirements.txt

@eliotwrobson This PR updates the CI jobs to run against GitHub Actions. It also adds runs the build and lint commands against multiple Python versions to ensure we aren't relying on any type features added since Python 3.8.
I _think_ I implemented everything correctly. It took a few tries to get CI working, but the issues were mostly fixed by upgrading certain dependencies in the toolchain.

Add Python 3.12 to CI matrix

---

automata/base/utils.py
automata/fa/dfa.py
automata/fa/nfa.py

Resolves #202. @Tagl you can try this version of the code and see if it gives you the speedup you want.

Predecessor speed fix

---

CONTRIBUTING.md
automata/fa/dfa.py
automata/fa/gnfa.py
automata/tm/tape.py

@eliotwrobson With recent projects, I have had a change of perspective with regard to coverage. Rather than trying to achieve an often-unattainable 100% coverage score (even by excluding lines/branches that logically cannot be covered), I have reasoned it is better to give an honest and accurate score.
Because, of course, anyone can achieve a 100% code coverage score by ignoring lines/branches, and I would prefer to have the coverage scores in my projects be accurate reflections of the analysis, rather than cutting corners in the interest of "perfection".
Therefore, this PR removes all `# pragma: no cover` and `# pragma: no branch` directives, and updates the Contributing guide to remove any strict (or even implied requirement) for exact 100% coverage. Of course, we want as much to be …

Do not exclude any lines/branches from coverage report

---

automata/fa/dfa.py
tests/test_dfa.py

Closes #162 
@caleb531 @eliotwrobson 
Haven't added tests for full coverage but I've done a fair bit of manual testing and it is producing correct results.
The DFA produced isn't necessarily minimal (consider {"ab", "abba"}) but it's certainly faster than taking multiple unions.
I've been trying to cut it down to a single BFS and then remove the object oriented nodes but there's always something that just isn't clicking for me, so I'm keeping it like this for now, maybe you will spot it.
I have to put this on hold on my end for a few days.

Aho-Corasick

---

README.md

Added a dynamic badge to display supported Python versions and a docs building badge (since this was something requested as part of the ongoing review): https://github.com/pyOpenSci/software-submission/issues/152#issuecomment-2016551272

docs: Add more badges

---

automata/fa/dfa.py
tests/test_dfa.py

Fixes small bug in the minify function for partial DFAs and the as_partial check for a DFA creation function.
I think this raises the question, @caleb531 should the allow_partial be a computed property in the constructor if it is manually set by the user? i.e., if client code sets this property to true, should it be set to `False` if the transition dictionary is not partial.

fix: Fix bug in minify edge case

---

automata/fa/dfa.py
tests/test_dfa.py

Change the checks for behavior when dealing with partial DFAs. Resolves https://github.com/caleb531/automata/issues/219 @caleb531

Partial behavior change and corresponding tests

---

automata/fa/dfa.py
tests/test_dfa.py

Closes #207 
Might be wise to add a few more tests.

Successors length limits

---

automata/fa/nfa.py
automata/regex/parser.py
automata/regex/regex.py
tests/test_regex.py

Linked to #232.
Changed the order in which the tokens are registered in the regex lexer to process the rule about recognizing letters last, and changed that rule to account for all non-blank characters (as specified per python's `re` library with `\S`).
Added a test to check for the support of non-ascii characters.
This is my very first pull request ever so feel free to guide me.

Unicode characters support in regex

---

.vscode/extensions.json
.vscode/settings.json

Since we're using Flake8 and black, we should put the 88-line ruler, which is black's default maximum line length, so I added `"editor.rulers": [88]` to `.vscode/settings.json`.
On the other hand, `"isort.args"` is only available if we install [ms-python.isort](https://marketplace.visualstudio.com/items?itemName=ms-python.isort), which is why I added it to `.vscode/extensions.json`.

Updated settings.json + ms-python.isort as recommended extension

---

automata/tm/mntm.py
pyproject.toml
tests/test_mntm.py

Completed also `test_read_input_as_ntm()` to be able to detect whether the tapes are different after running an MNTM normally and as an NTM (which would have detected that both `mntm.accepts_input(input_str))` and `mntm.read_input_stepwise(input_str)` weren't working in unison.
Now, the following code does work:
```
from automata.tm.mntm import MNTM
mntm = MNTM(
states={"q0", "q1", "q2", "q3", "q4"},
input_symbols={"0", "1"},
tape_symbols={"0", "1", "$", "#"},
n_tapes=3,
transitions={
"q0": {
("0", "#", "#"): [("q1", (("0", "N"), ("$", "R"), ("$", "R")))],
("1", "#", "#"): [("q1", (("1", "N"), ("$", "R"), ("$", "R")))],
},
"q1": {
("0", "#", "#"): [
("q1", (("0", "R"), ("0", "R"), ("#", "N"))),
("q2", (("0", "R"), ("#", "N"), ("0", "R"))),
],
("1", "#", "#"): [
("q1", (("1", "R"), ("1", …
```

Fixed MNTM's implementation of read_input_as_ntm

---

.github/workflows/lint.yml
.github/workflows/tests.yml
.gitignore
.vscode/settings.json
CONTRIBUTING.md
pyproject.toml
uv.lock

@eliotwrobson I realized we forgot to update the Contributing guide with documentation on how to set up `uv`. I've updated it below, along with a few other necessary improvements (like adding uv's default virtualenv name to our `.gitignore`).
Please take a look and let me know what you think!

`uv` improvements
